### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by NormalErik** [tobiasfrck/Playground_Projekt#1]
eg.:
```
## .gitignore file

## Visual Studio specific
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History for Visual Studio Code
.history/

# Built Visual Studio Code Extensions
*.vsix

Ref.: https://github.com/github/gitignore/blob/main/Global/VisualStudioCode.gitignore
```

**Comment by tobiasfrck** [comment]
I will add a gitignore but a **Visual Studio** ~Code~ version is more suitable since that is what I am working with. VSCode seems to need a little more setup to work with MonoGame.

**Comment by NormalErik** [comment]
Ah i see. So it would not directly work with other IDE's like IntelliJ?

**Comment by tobiasfrck** [comment]
I think so because I assume IntelliJ uses a different file structure.
